class Token:
    tokens = (
        'INT',
        'FLOAT',
        'IDENTIFIER',
        'PLUS',
        'MINUS',
        'TIMES',
        'DIVIDE',
        'POWER',
        'LPAREN',
        'RPAREN',
        'ASSIGN',
        'VAR',
        'AND',
        'OR',
        'NOT',
        'BOOL',
        'EQT',
        'NEQ',
        'LT',
        'GT',
        'ELT',
        'EGT',
        'NEWLINE',
        'SEMICOLON',
    )